name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx nx report
        shell: bash
      - name: Get Package Name From Release
        id: get_pkg_name
        run: |
          RELEASE_TAG_NAME=$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f1')
          FULL_PKG_NAME="@nostagik/${RELEASE_TAG_NAME}"
          echo "FULL_PKG_NAME=$FULL_PKG_NAME" >> $GITHUB_OUTPUT
      - name: Publish packages
        run: npx nx run ${{ steps.get_pkg_name.outputs.FULL_PKG_NAME }}:publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
